angular.module('precios.services', [])

  .factory('Categories', function() {
    
    var categories = [
      {"id":"2","name":"bebidas","length":20},
      {"id":"3","name":"carnes y procesados","length":14},
      {"id":"4","name":"lacteos","length":23},
      {"id":"5","name":"limpieza","length":20},
      {"id":"6","name":"panificados","length":6},
      {"id":"1","name":"almacen","length":76},
      {"id":"7","name":"perfumeria","length":21},
      {"id":"8","name":"verduleria","length":10},
      {"id":"9","name":"escolar","length":35},
    ];

    return {
      all: function() {
        return categories;
      },
      get: function(cateogryId) {
        return categories[cateogryId - 1];
      }
    };

  })

 .factory('Products', function() {
  
  var products = [
    {"id":"1","price":"10,85","priceperunity":"7,23\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 1500 CC","category":"1","brand":"ZANONI","supplier":"AFA"},
    {"id":"2","price":"6,52","priceperunity":"7,24\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 900 CC","category":"1","brand":"ZANONI","supplier":"AFA"},
    {"id":"3","price":"7,60","priceperunity":"8,45\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 900 CC","category":"1","brand":"NATURA","supplier":"AGD"},
    {"id":"4","price":"6,52","priceperunity":"7,24\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 900 CC","category":"1","brand":"ALSAMAR","supplier":"BUNGE"},
    {"id":"5","price":"10,85","priceperunity":"7,23\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 1500 CC","category":"1","brand":"CORAZON \/ GERSOL","supplier":"GERMAIZ"},
    {"id":"6","price":"7,32","priceperunity":"8,13\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 900 CC","category":"1","brand":"CA\u00d1UELAS","supplier":"MOLINOS CA\u00d1UELAS"},
    {"id":"7","price":"11,80","priceperunity":"7,87\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 1500 CC","category":"1","brand":"CA\u00d1UELAS","supplier":"MOLINOS CA\u00d1UELAS"},
    {"id":"8","price":"12,02","priceperunity":"8,01\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 1500 CC","category":"1","brand":"COCINERO","supplier":"MOLINOS RIO DE LA PLATA"},
    {"id":"9","price":"7,54","priceperunity":"8,38\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 900 CC","category":"1","brand":"COCINERO","supplier":"MOLINOS RIO DE LA PLATA"},
    {"id":"10","price":"10,92","priceperunity":"7,28\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 1500 CM3","category":"1","brand":"LEG\u00edTIMO","supplier":"NIDERA"},
    {"id":"11","price":"6,57","priceperunity":"7,3\/LITRO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 900 CM3","category":"1","brand":"LEG\u00edTIMO","supplier":"NIDERA"},
    {"id":"12","price":"6,93","priceperunity":"7,7\/KILO","product":"ACEITE DE GIRASOL BOTELLA DE PLASTICO - 900 CM3","category":"1","brand":"COSTA DEL SOL","supplier":"TANONI"},
    {"id":"13","price":"12,12","priceperunity":"8,08\/LITRO","product":"ACEITE MEZCLA BOTELLA DE PLASTICO - 1500 CM3","category":"1","brand":"CADA D\u00edA","supplier":"AGD"},
    {"id":"14","price":"7,60","priceperunity":"8,45\/LITRO","product":"ACEITE MEZCLA BOTELLA DE PLASTICO - 900 CM3","category":"1","brand":"CADA D\u00edA","supplier":"AGD"},
    {"id":"15","price":"10,85","priceperunity":"7,23\/LITRO","product":"ACEITE MEZCLA BOTELLA DE PLASTICO - 1500 CM3","category":"1","brand":"EL RELICARIO","supplier":"GERMA\u00edZ"},
    {"id":"16","price":"12,02","priceperunity":"8,01\/LITRO","product":"ACEITE MEZCLA BOTELLA DE PLASTICO - 1500 CM3","category":"1","brand":"IDEAL","supplier":"MOLINOS RIO DE LA PLATA"},
    {"id":"17","price":"7,54","priceperunity":"8,38\/LITRO","product":"ACEITE MEZCLA BOTELLA DE PLASTICO - 900 CM3","category":"1","brand":"IDEAL","supplier":"MOLINOS RIO DE LA PLATA"},
    {"id":"18","price":"6,52","priceperunity":"7,24\/LITRO","product":"ACEITE MEZCLA BOTELLA DE PLASTICO - 900 CM3","category":"1","brand":"BELLA FLOR","supplier":"NIEUW WERELD"},
    {"id":"19","price":"5,57","priceperunity":"6,19\/LITRO","product":"ACEITE MEZCLA BOTELLA DE PLASTICO - 900 CM3","category":"1","brand":"MAROLIO","supplier":"VICENT\u00edN"},
    {"id":"20","price":"12,99","priceperunity":"25,98\/KILO","product":"ARROZ DOBLE CAROLINA - 500 G","category":"1","brand":"GALLO","supplier":"MOLINOS R\u00cdO DE LA PLATA"},
    {"id":"21","price":"4,80","priceperunity":"9,6\/KILO","product":"ARROZ LARGO FINO 00000 LARGO FINO 00000 - 500 G","category":"1","brand":"MOLINOS ALA","supplier":"ADECO AGRO"},
    {"id":"22","price":"5,90","priceperunity":"16,86\/KILO","product":"ARVEJAS EN LATA - 350 G","category":"1","brand":"ALCO","supplier":"GRUPO CANALE"},
    {"id":"23","price":"3,70","priceperunity":"12,33\/KILO","product":"ARVEJAS EN LATA - 300 G","category":"1","brand":"NOEL","supplier":"ARCOR"},
    {"id":"24","price":"9,50","priceperunity":"55,88\/KILO","product":"ATUN AL NATURAL DESMENUZADO - 170 G","category":"1","brand":"G\u00d3MES DA COSTA","supplier":"GDC ARGENTINA GRUPO CALVO"},
    {"id":"25","price":"20,50","priceperunity":"120,59\/KILO","product":"ATUN AL NATURAL EN LATA - 170 G","category":"1","brand":"LA CAMPAGNOLA","supplier":"ARCOR"},
    {"id":"26","price":"6,00","priceperunity":"6\/KILO","product":"AZUCAR BLANCA - 1 KG","category":"1","brand":"DOMINO","supplier":"LEDESMA"},
    {"id":"27","price":"7,30","priceperunity":"7,3\/KILO","product":"AZUCAR BLANCA - 1 KG","category":"1","brand":"LEDESMA","supplier":"LEDESMA"},
    {"id":"28","price":"7,30","priceperunity":"7,3\/KILO","product":"AZUCAR BLANCA - 1 KG","category":"1","brand":"CHANGO","supplier":"TABACAL AGROINDUSTRIA"},
    {"id":"29","price":"7,70","priceperunity":"42,78\/KILO","product":"CACAO EN POLVO - 180 G","category":"1","brand":"TODDY","supplier":"PEPSICO"},
    {"id":"30","price":"14,80","priceperunity":"59,2\/KILO","product":"CAF\u00c9 MOLIDO - 250 G","category":"1","brand":"LA MORENITA","supplier":"LA VIRGINIA"},
    {"id":"31","price":"7,90","priceperunity":"69,3\/KILO","product":"CALDO DE GALLINA - 114 G","category":"1","brand":"MAGGI","supplier":"NESTL\u00c9 ARGENTINA"},
    {"id":"32","price":"7,99","priceperunity":"70,09\/KILO","product":"CALDO DE GALLINA - 114 G","category":"1","brand":"WILDE","supplier":"UNILEVER"},
    {"id":"33","price":"31,00","priceperunity":"44,29\/KILO","product":"DULCE DE BATATA - 700 G","category":"1","brand":"CANALE","supplier":"GRUPO CANALE"},
    {"id":"34","price":"9,99","priceperunity":"24,98\/KILO","product":"DULCE DE LECHE ENTERO CL\u00c1SICO NO REPOSTERO - 400 G","category":"1","brand":"ILOLAY","supplier":"SUCESORES DE ALFREDO WILLINER"},
    {"id":"35","price":"12,10","priceperunity":"30,25\/KILO","product":"DULCE DE LECHE ENTERO CL\u00c1SICO POTE - 400 G","category":"1","brand":"LA SEREN\u00cdSIMA","supplier":"MASTELLONE"},
    {"id":"36","price":"5,50","priceperunity":"11\/KILO","product":"FIDEOS SECOS TIPO GUISEROS CODITOS - 500 G","category":"1","brand":"PASTAS CANALE","supplier":"TERRABUSI-KRAFT MONDELEZ"},
    {"id":"37","price":"7,40","priceperunity":"14,8\/KILO","product":"FIDEOS SECOS TIPO GUISEROS MOSTACHOLES - 500 G","category":"1","brand":"MANERA","supplier":"MOLINOS R\u00cdO DE LA PLATA"},
    {"id":"38","price":"7,00","priceperunity":"14\/KILO","product":"FIDEOS SECOS TIPO TALLAR\u00cdN TALLAR\u00cdN - 500 G","category":"1","brand":"FAVORITA","supplier":"MOLINOS R\u00cdO DE LA PLATA"},
    {"id":"39","price":"6,50","priceperunity":"13\/KILO","product":"FIDEOS SECOS TIPO TALLAR\u00cdN TALLAR\u00cdN - 500 G","category":"1","brand":"PASTAS CANALE","supplier":"TERRABUSI-KRAFT MONDELEZ"},
    {"id":"40","price":"3,50","priceperunity":"0,02\/C\/U","product":"FOSFOROS - 220 UN","category":"1","brand":"RANCHERA","supplier":"COMPA\u00d1\u00cdA GENERAL DE FOSFOROS SUDAMERICANA S.A."},
    {"id":"41","price":"4,84","priceperunity":"43,97\/KILO","product":"GALLETITAS DE AGUA COMUNES ENVASADAS - 110 G","category":"1","brand":"MEDIA TARDE","supplier":"ARCOR"},
    {"id":"42","price":"4,40","priceperunity":"36,37\/KILO","product":"GALLETITAS DE AGUA COMUNES ENVASADAS SINGLE - 120 G","category":"1","brand":"EXPRESS CLASICAS PARAGUAS","supplier":"TERRABUSI-KRAFT MONDELEZ"},
    {"id":"43","price":"13,40","priceperunity":"28,82\/KILO","product":"GALLETITAS DULCES ENVASADAS SECAS SIN RELLENO - 465 G","category":"1","brand":"VOCACI\u00d3N","supplier":"ARCOR"},
    {"id":"44","price":"5,40","priceperunity":"35,29\/KILO","product":"GALLETITAS DULCES ENVASADAS SECAS SIN RELLENO CHOCOLATE - 153 G","category":"1","brand":"LINCOLN CHOCO","supplier":"TERRABUSI-KRAFT MONDELEZ"},
    {"id":"45","price":"6,20","priceperunity":"38,75\/KILO","product":"GALLETITAS DULCES ENVASADAS SECAS SIN RELLENO INDIVIDUAL - 160 G","category":"1","brand":"BOCA DE DAMA","supplier":"TERRABUSI-KRAFT MONDELEZ"},
    {"id":"46","price":"5,79","priceperunity":"11,58\/KILO","product":"HARINA DE MAIZ (POLENTA) - 500 G","category":"1","brand":"MAGICA","supplier":"PEPSICO"},
    {"id":"47","price":"7,99","priceperunity":"7,99\/KILO","product":"HARINA DE TRIGO 0000 DE 0000 - 1 KG","category":"1","brand":"BLANCAFLOR","supplier":"MOLINOS R\u00cdO DE LA PLATA"},
    {"id":"48","price":"6,35","priceperunity":"6,35\/KILO","product":"HARINA DE TRIGO COMUN 000 COM\u00daN 000 - 1 KG","category":"1","brand":"CA\u00d1UELAS","supplier":"MOLINOS CA\u00d1UELAS"},
    {"id":"49","price":"7,27","priceperunity":"7,27\/KILO","product":"HARINA DE TRIGO COMUN 000 COM\u00daN 000 - 1 KG","category":"1","brand":"FAVORITA","supplier":"MOLINOS R\u00cdO DE LA PLATA"},
    {"id":"50","price":"30,37","priceperunity":"5,06\/UNIDAD","product":"HELADO LIMON CAJA X 6 UNIDADES - 6 UN","category":"1","brand":"TORPEDO","supplier":"NESTL\u00c9 ARGENTINA"},
    {"id":"51","price":"8,55","priceperunity":"1,43\/C\/U","product":"HUEVOS BLANCOS - 6 UN","category":"1","brand":"AVICOPER","supplier":"NUESTRA HUELLA"},
    {"id":"52","price":"8,55","priceperunity":"1,43\/C\/U","product":"HUEVOS BLANCOS - 6 UN","category":"1","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"53","price":"11,29","priceperunity":"37,63\/KILO","product":"LENTEJAS SECAS REMOJADAS EN LATA - 300 G","category":"1","brand":"LA CAMPAGNOLA","supplier":"ARCOR"},
    {"id":"54","price":"8,75","priceperunity":"25\/KILO","product":"LENTEJAS SECAS REMOJADAS EN LATA - 350 G","category":"1","brand":"INALPA","supplier":"INALPA"},
    {"id":"55","price":"7,30","priceperunity":"14,6\/LITRO","product":"MAYONESA COM\u00daN - 500 CM3","category":"1","brand":"MENOYO","supplier":"MENOYO S.A."},
    {"id":"56","price":"7,90","priceperunity":"16,29\/KILO","product":"MAYONESA COM\u00daN SACHET - 485 G","category":"1","brand":"RI-K MAY DOYP","supplier":"UNILEVER"},
    {"id":"57","price":"14,55","priceperunity":"32,05\/KILO","product":"MERMELADA DE CIRUELA FRASCO DE VIDRIO - 454 G","category":"1","brand":"ARCOR","supplier":"ARCOR"},
    {"id":"58","price":"13,00","priceperunity":"28,63\/KILO","product":"MERMELADA DE DURAZNO FRASCO DE VIDRIO - 454 G","category":"1","brand":"CANALE","supplier":"GRUPO CANALE"},
    {"id":"59","price":"6,80","priceperunity":"19,43\/KILO","product":"POROTOS EN LATA - 350 G","category":"1","brand":"ARCOR","supplier":"ARCOR"},
    {"id":"60","price":"5,30","priceperunity":"10,19\/KILO","product":"PURE DE TOMATE TETRA PACK - 520 G","category":"1","brand":"ALCO","supplier":"GRUPO CANALE"},
    {"id":"61","price":"5,00","priceperunity":"9,62\/KILO","product":"PURE DE TOMATE TETRA PACK - 520 G","category":"1","brand":"ARCOR","supplier":"ARCOR"},
    {"id":"62","price":"5,00","priceperunity":"10\/KILO","product":"SAL FINA ESTUCHE - 500 G","category":"1","brand":"CELUSAL","supplier":"INDUSTRIAS QUIMICAS Y MINERAS TIMBO S.A."},
    {"id":"63","price":"4,25","priceperunity":"8,5\/KILO","product":"SAL FINA PAQUETE DE PAPEL - 500 G","category":"1","brand":"DOS ANCLAS","supplier":"CIA.INTRODUCTORA BS.AS."},
    {"id":"64","price":"5,70","priceperunity":"5,7\/KILO","product":"SAL GRUESA PAQUETE DE PAPEL - 1 KG","category":"1","brand":"DOS ANCLAS","supplier":"CIA.INTRODUCTORA BS.AS."},
    {"id":"65","price":"5,45","priceperunity":"5,45\/KILO","product":"SAL GRUESA PAQUETE DE PAPEL - 1 KG","category":"1","brand":"CELUSAL","supplier":"INDUSTRIAS QUIMICAS Y MINERAS TIMBO S.A."},
    {"id":"66","price":"5,40","priceperunity":"23,48\/KILO","product":"TAPA DE TARTA - 230 G","category":"1","brand":"LA SALTE\u00d1A","supplier":"GENERAL MILLS"},
    {"id":"67","price":"9,50","priceperunity":"23,75\/KILO","product":"TAPA DE TARTA PASCUALINA BAJO SODIO - 400 G","category":"1","brand":"MEND\u00cdA","supplier":"CASAMEN"},
    {"id":"68","price":"15,10","priceperunity":"27,96\/KILO","product":"TAPAS PARA EMPANADAS CRIOLLA - 20 UN","category":"1","brand":"LA SALTE\u00d1A","supplier":"GENERAL MILLS"},
    {"id":"69","price":"4,60","priceperunity":"0,184\/UNIDAD","product":"TE COM\u00daN EN SAQUITOS - 25 UN","category":"1","brand":"TARAG\u00dc\u00cd","supplier":"ESTABLECIMIENTO LAS MARIAS S.A."},
    {"id":"70","price":"4,40","priceperunity":"0,176\/UNIDAD","product":"TE COM\u00daN EN SAQUITOS - 25 UN","category":"1","brand":"LA MORENITA","supplier":"LA VIRGINIA"},
    {"id":"71","price":"7,00","priceperunity":"17,5\/KILO","product":"TOMATE PERITA EN LATA - 400 G","category":"1","brand":"ALCO","supplier":"GRUPO CANALE"},
    {"id":"72","price":"5,70","priceperunity":"14,25\/KILO","product":"TOMATE PERITA EN LATA - 400 G","category":"1","brand":"NOEL","supplier":"ARCOR"},
    {"id":"73","price":"4,80","priceperunity":"9,6\/LITRO","product":"VINAGRE DE ALCOHOL - 500 ML","category":"1","brand":"DOS ANCLAS","supplier":"CIA.INTRODUCTORA BS.AS."},
    {"id":"74","price":"6,70","priceperunity":"13,4\/LITRO","product":"VINAGRE DE ALCOHOL - 500 ML","category":"1","brand":"MENOYO","supplier":"MENOYO S.A."},
    {"id":"75","price":"27,00","priceperunity":"27\/KILO","product":"YERBA MATE CON PALO - 1 KG","category":"1","brand":"AMANDA","supplier":"LA CACHUERA SA"},
    {"id":"76","price":"17,75","priceperunity":"35,5\/KILO","product":"YERBA MATE CON PALO BAJO CONTENIDO EN POLVO - 500 G","category":"1","brand":"UNI\u00d3N","supplier":"ESTABLECIMIENTO LAS MARIAS S.A."},

    {"id":"77","price":"9,00","priceperunity":"9\/LITRO","product":"AGUA MINERALIZADA SODA (NO DISPONIBLE EN AMBA) - LT","category":"2","brand":"KIN","supplier":"COCA COLA FEMSA"},
    {"id":"78","price":"9,90","priceperunity":"10,21\/LITRO","product":"CERVEZA BAJO CERO - 970 ML","category":"2","brand":"QUILMES","supplier":"CERVEC Y MALTERIA QUILMES SAI"},
    {"id":"79","price":"9,30","priceperunity":"9,59\/LITRO","product":"CERVEZA RUBIA - 970 ML","category":"2","brand":"BIECKERT","supplier":"GRUPO CCU"},
    {"id":"80","price":"12,50","priceperunity":"8,33\/LITRO","product":"GASEOSA COLA - 1,5 LT","category":"2","brand":"COCA COLA","supplier":"COCA COLA FEMSA"},
    {"id":"81","price":"9,20","priceperunity":"6,13\/LITRO","product":"GASEOSA COLA - 1,5 LT","category":"2","brand":"CUNNINGTON","supplier":"PRODEA"},
    {"id":"82","price":"12,50","priceperunity":"8,33\/LITRO","product":"GASEOSA LIMA LIM\u00d3N - 1,5 LT","category":"2","brand":"SEVEN UP","supplier":"CERVEC Y MALTERIA QUILMES SAI"},
    {"id":"83","price":"9,20","priceperunity":"6,13\/LITRO","product":"GASEOSA LIMA LIM\u00d3N - 1,5 LT","category":"2","brand":"CUNNINGTON","supplier":"PRODEA"},
    {"id":"84","price":"7,75","priceperunity":"5,17\/LITRO","product":"JUGO CONCENTRADO DE NARANJA - 1,5 LT","category":"2","brand":"CARIOCA","supplier":"COCA COLA FEMSA"},
    {"id":"85","price":"7,50","priceperunity":"5\/LITRO","product":"JUGO CONCENTRADO DE NARANJA - 1,5 LT","category":"2","brand":"MOCORET\u00c1","supplier":"RPB"},
    {"id":"86","price":"9,50","priceperunity":"9,5\/LITRO","product":"JUGO DE NARANJA SIN DILUIR NUTRI DEFENSAS - 1 LT","category":"2","brand":"CEPITA","supplier":"COCA COLA FEMSA"},
    {"id":"87","price":"2,90","priceperunity":"14,5\/LITRO","product":"JUGO SIN DILUIR DE NARANJA - 200 ML","category":"2","brand":"BAGGIO","supplier":"RPB"},
    {"id":"88","price":"1,60","priceperunity":"213,33\/KILO","product":"JUGOS EN POLVO ANANA - 7,5 G","category":"2","brand":"SER","supplier":"AGUAS DANONE DE ARGENTINA S.A."},
    {"id":"89","price":"1,60","priceperunity":"166,67\/KILO","product":"JUGOS EN POLVO MANZANA - 9,6 G","category":"2","brand":"SER","supplier":"AGUAS DANONE DE ARGENTINA S.A."},
    {"id":"90","price":"1,60","priceperunity":"64\/KILO","product":"JUGOS EN POLVO MULTIFRUTA - 25 G","category":"2","brand":"ARCOR","supplier":"ARCOR"},
    {"id":"91","price":"1,60","priceperunity":"125\/KILO","product":"JUGOS EN POLVO NARANJA - 12,8 G","category":"2","brand":"SER","supplier":"AGUAS DANONE DE ARGENTINA S.A."},
    {"id":"92","price":"1,60","priceperunity":"153,85\/KILO","product":"JUGOS EN POLVO NARANJA DULCE - 10,4 G","category":"2","brand":"SER","supplier":"AGUAS DANONE DE ARGENTINA S.A."},
    {"id":"93","price":"1,60","priceperunity":"207,79\/KILO","product":"JUGOS EN POLVO NARANJA DURAZNO - 7,7 G","category":"2","brand":"SER","supplier":"AGUAS DANONE DE ARGENTINA S.A."},
    {"id":"94","price":"7,05","priceperunity":"3,13\/LITRO","product":"SODA BOTELLA DE PLASTICO - 2,25 LT","category":"2","brand":"SIERRA DE LOS PADRES","supplier":"NUTRECO ALIMENTOS S.A.\/ 2 NIGUIL"},
    {"id":"95","price":"10,40","priceperunity":"10,4\/LITRO","product":"VINO COMUN TINTO TETRABRICK - 1 LT","category":"2","brand":"FACUNDO","supplier":"PE\u00d1AFLOR"},
    {"id":"96","price":"9,05","priceperunity":"9,05\/LITRO","product":"VINO COMUN TINTO TETRABRICK - 1 LT","category":"2","brand":"UVITA","supplier":"RPB"},

    {"id":"97","price":"26,00","priceperunity":"26\/KILO","product":"CARNE PICADA - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"98","price":"49,00","priceperunity":"49,00 \/KILO","product":"CUADRADA - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"99","price":"22,00","priceperunity":"65,87\/KILO","product":"HAMBURGUESAS DE CARNE TRADICIONALES DE 332-334GR - 4 UN","category":"3","brand":"PATY","supplier":"QUICKFOOD"},
    {"id":"100","price":"12,00","priceperunity":"12,00 \/KILO","product":"HUESO CON CARNE DE NOVILLO - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"101","price":"90,00","priceperunity":"90,00 \/KILO","product":"JAMON COCIDO - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"102","price":"36,00","priceperunity":"36,00 \/KILO","product":"MARUCHA - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"103","price":"18,90","priceperunity":"68,48\/KILO","product":"MEDALLON CARNE VACUNA CONGELADA 276 GR - 4 UN","category":"3","brand":"SWIFT","supplier":"JBS"},
    {"id":"104","price":"18,50","priceperunity":"18,50 \/KILO","product":"POLLO CONGELADO SIN MENUDOS - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"105","price":"18,50","priceperunity":"18,5\/KILO","product":"POLLO ENTERO FRESCO CON MENUDOS - 1 KG","category":"3","brand":"TODAS LAS MARCAS","supplier":"CENTRO DE EMPRESAS DE PROCESADORAS AV\u00cdCOLAS"},
    {"id":"106","price":"40,00","priceperunity":"40,00 \/KILO","product":"ROAST BEEF DE NOVILLO - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"107","price":"9,70","priceperunity":"43,11\/KILO","product":"SALCHICHAS TIPO VIENA CON PIEL - 6 UN","category":"3","brand":"SWIFT","supplier":"JBS"},
    {"id":"108","price":"10,40","priceperunity":"46,67\/KILO","product":"SALCHICHAS TIPO VIENA CON PIEL - 6 UN","category":"3","brand":"PATY VIENA","supplier":"QUICKFOOD"},
    {"id":"109","price":"42,00","priceperunity":"42,00 \/KILO","product":"TAPA DE ASADO DE NOVILLO - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"110","price":"44,00","priceperunity":"44,00 \/KILO","product":"TAPA DE NALGA DE NOVILLO - 1 KG","category":"3","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},

    {"id":"111","price":"7,99","priceperunity":"39,95\/LITRO","product":"CREMA DE LECHE ENTERA POTE - 200 CM3","category":"4","brand":"MILKAUT","supplier":"MILKAUT"},
    {"id":"112","price":"9,00","priceperunity":"36\/LITRO","product":"CREMA UAT - 250 CM3","category":"4","brand":"SANCOR","supplier":"SANCOR"},
    {"id":"113","price":"7,20","priceperunity":"7,20 \/LITRO","product":"LECHE COMUN DESCREMADA LIQUIDA SACHET - 1 LT","category":"4","brand":"LA SEREN\u00cdSIMA","supplier":"MASTELLONE"},
    {"id":"114","price":"7,20","priceperunity":"7,2\/LITRO","product":"LECHE COMUN DESCREMADA LIQUIDA SACHET - 1 LT","category":"4","brand":"SANCOR","supplier":"SANCOR"},
    {"id":"115","price":"6,90","priceperunity":"6,9\/LITRO","product":"LECHE COMUN ENTERA SACHET - 1 LT","category":"4","brand":"SANCOR","supplier":"SANCOR"},
    {"id":"116","price":"6,90","priceperunity":"6,90 \/LITRO","product":"LECHE COMUN ENTERA ULTRAPASTEURIZADA (C\/CALCIO VIT A\/D B9 ) SACHET - 1 LT","category":"4","brand":"LA SEREN\u00cdSIMA","supplier":"MASTELLONE"},
    {"id":"117","price":"11,66","priceperunity":"58,31\/KILO","product":"LECHE EN POLVO ENTERA PAQUETE - 200 G","category":"4","brand":"LA SEREN\u00cdSIMA","supplier":"MASTELLONE"},
    {"id":"118","price":"29,90","priceperunity":"74,75\/KILO","product":"LECHE EN POLVO ENTERA PAQUETE - 400 G","category":"4","brand":"NIDO","supplier":"NESTL\u00c9 ARGENTINA"},
    {"id":"119","price":"8,36","priceperunity":"8,36\/LITRO","product":"LECHE ENTERA LARGA VIDA UAT - 1 LT","category":"4","brand":"MILKAUT","supplier":"MILKAUT"},
    {"id":"120","price":"8,99","priceperunity":"8,99\/LITRO","product":"LECHE ENTERA LARGA VIDA U A T - 1 LT","category":"4","brand":"VER\u00d3NICA","supplier":"VER\u00d3NICA S.A."},
    {"id":"121","price":"10,90","priceperunity":"54,9\/KILO","product":"MANTECA - 200 G","category":"4","brand":"MILKAUT","supplier":"MILKAUT"},
    {"id":"122","price":"11,50","priceperunity":"57,5\/KILO","product":"MANTECA CALIDAD EXTRA VITAMINAS A Y E - 200 G","category":"4","brand":"LA SEREN\u00cdSIMA","supplier":"MASTELLONE"},
    {"id":"123","price":"5,30","priceperunity":"44,17\/KILO","product":"POSTRE NI\u00d1O CHOCOLATE - 120 G","category":"4","brand":"SHIMY","supplier":"SANCOR"},
    {"id":"124","price":"5,30","priceperunity":"44,17\/KILO","product":"POSTRE NI\u00d1O CHOCOLATE Y DULCE DE LECHE - 120 G","category":"4","brand":"SHIMY","supplier":"SANCOR"},
    {"id":"125","price":"5,30","priceperunity":"44,17\/KILO","product":"POSTRE NI\u00d1O DULCE DE LECHE - 120 G","category":"4","brand":"SHIMY","supplier":"SANCOR"},
    {"id":"126","price":"7,95","priceperunity":"49,38\/KILO","product":"POSTRE NI\u00d1O VAINILLA - 161 G","category":"4","brand":"DANONINO","supplier":"DANONE"},
    {"id":"127","price":"5,30","priceperunity":"44,17\/KILO","product":"POSTRE NI\u00d1O VAINILLA - 120 G","category":"4","brand":"SHIMY","supplier":"SANCOR"},
    {"id":"128","price":"5,30","priceperunity":"44,17\/KILO","product":"POSTRE NI\u00d1O VAINILLA Y DULCE DE LECHE - 120 G","category":"4","brand":"SHIMY","supplier":"SANCOR"},
    {"id":"129","price":"17,00","priceperunity":"56,57\/KILO","product":"QUESO CREMA ENTERO - 300 G","category":"4","brand":"MENDICRIM","supplier":"SANCOR"},
    {"id":"130","price":"47,00","priceperunity":"47,00 \/KILO","product":"QUESO CREMOSO - 1 KG","category":"4","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"131","price":"15,99","priceperunity":"133,25\/KILO","product":"QUESO RALLADO PAQUETE - 120 G","category":"4","brand":"TREGAR","supplier":"GARC\u00cdA HNOS. AGROINDUSTRIAL"},
    {"id":"132","price":"18,50","priceperunity":"154,17\/KILO","product":"QUESO RALLADO PAQUETE - 120 G","category":"4","brand":"LA SEREN\u00cdSIMA","supplier":"MASTELLONE"},
    {"id":"133","price":"8,00","priceperunity":"45,98\/KILO","product":"YOGUR DESCREMADO CON MUESLI - 174 G","category":"4","brand":"SER","supplier":"DANONE"},

    {"id":"134","price":"19,90","priceperunity":"22,16\/LITRO","product":"AUTOBRILLO INCOLORO - 900 CM3","category":"5","brand":"SUIZA","supplier":"CERA SUIZA"},
    {"id":"135","price":"19,90","priceperunity":"22,11\/LITRO","product":"AUTOBRILLO NEGRO - 900 CM3","category":"5","brand":"SUIZA","supplier":"CERA SUIZA"},
    {"id":"136","price":"19,90","priceperunity":"22,14\/LITRO","product":"AUTOBRILLO ROJO - 900 CM3","category":"5","brand":"SUIZA","supplier":"CERA SUIZA"},
    {"id":"137","price":"8,85","priceperunity":"11,8\/LITRO","product":"DETERGENTE LIQUIDO PARA VAJILLA CREM COLAGENO - 750 ML","category":"5","brand":"ALA","supplier":"UNILEVER"},
    {"id":"138","price":"3,99","priceperunity":"3,99\/C\/U","product":"ESPONJA PARA LAVAR PLATOS LISA DELGADA - 1 UN","category":"5","brand":"MORTIMER","supplier":"CLOROX ARGENTINA S.A."},
    {"id":"139","price":"5,50","priceperunity":"13,75\/KILO","product":"JABON BLANCO EN POLVO ALTA ESPUMA NATURAL FRESH - 400 G","category":"5","brand":"ZORRO","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"140","price":"10,60","priceperunity":"13,25\/KILO","product":"JABON BLANCO EN POLVO BAJA ESPUMA NATURAL FRESH - 800 G","category":"5","brand":"ZORRO","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"141","price":"5,50","priceperunity":"13,75\/KILO","product":"JABON BLANCO EN POLVO BAJA ESPUMA NATURAL FRESH - 400 G","category":"5","brand":"ZORRO","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"142","price":"4,20","priceperunity":"28\/KILO","product":"JABON EN PAN ESFERAS ACTIVAS - 150 G","category":"5","brand":"ZORRO","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"143","price":"9,40","priceperunity":"11,75\/KILO","product":"JABON EN POLVO PARA LAVARROPAS REGULAR - 800 G","category":"5","brand":"QUERUB\u00cdN","supplier":"GRUPO QUERUCLOR"},
    {"id":"144","price":"9,40","priceperunity":"11,75\/KILO","product":"JABON EN POLVO PARA LAVARROPAS BAJA ESPUMA - 800 G","category":"5","brand":"QUERUB\u00cdN","supplier":"GRUPO QUERUCLOR"},
    {"id":"145","price":"14,54","priceperunity":"18,18\/KILO","product":"JABON EN POLVO PARA LAVARROPAS BAJA ESPUMA - 800 G","category":"5","brand":"ACE","supplier":"PROCTER AND GAMBLE"},
    {"id":"146","price":"5,17","priceperunity":"5,17\/LITRO","product":"LAVANDINA COMUN - 1 LT","category":"5","brand":"AYUD\u00cdN","supplier":"CLOROX ARGENTINA S.A."},
    {"id":"147","price":"4,59","priceperunity":"4,59\/LITRO","product":"LAVANDINA CONCENTRADA - 1 LT","category":"5","brand":"QUERUB\u00cdN","supplier":"GRUPO QUERUCLOR"},
    {"id":"148","price":"6,99","priceperunity":"18,64\/KILO","product":"LIMPIADOR FLORES DE NARANJA C\/ MICROPARTICULAS - 375 G","category":"5","brand":"CIF","supplier":"UNILEVER"},
    {"id":"149","price":"4,39","priceperunity":"8,78\/LITRO","product":"LIMPIADOR DESENGRASANTE REPUESTO DOY PACK - 500 ML","category":"5","brand":"MR. M\u00daSCULO","supplier":"S.C. JOHNSON Y SON DE ARG. S.A."},
    {"id":"150","price":"5,14","priceperunity":"10,28\/LITRO","product":"LIMPIADOR MULTIUSOS DOY PACK - 500 ML","category":"5","brand":"PROCENEX","supplier":"RECKITT BENCKISER"},
    {"id":"151","price":"12,74","priceperunity":"0,64\/M2","product":"PAPEL HIGIENICO HOJA SIMPLE 4 ROLLOS DE 50 METROS CADA UNO - 50 MTRS","category":"5","brand":"HIGIENOL","supplier":"PAPELERA DEL PLATA"},
    {"id":"152","price":"19,99","priceperunity":"0,65\/M2","product":"PAPEL HIGIENICO HOJA SIMPLE 4 ROLLOS DE 80 - 320 MTRS","category":"5","brand":"CAMPANITA","supplier":"CELULOSA CAMPANA"},
    {"id":"153","price":"13,00","priceperunity":"16,25\/KILO","product":"POLVO DE LAVADO GRANBY LAVADO TOTAL - 800 G","category":"5","brand":"GRANBY","supplier":"UNILEVER"},

    {"id":"154","price":"2,67","priceperunity":"2,67\/C\/U","product":"FACTURAS DE MANTECA - 1 UN","category":"6","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"155","price":"14,50","priceperunity":"38,16\/KILO","product":"PAN LACTAL BLANCO RODAJAS FINAS - 380 G","category":"6","brand":"LACTAL","supplier":"BIMBO DE ARGENTINA S.A."},
    {"id":"156","price":"18,70","priceperunity":"18,7\/KILO","product":"PAN MIGNON PANADER\u00cdA DEL SUPERMERCADO - 1 KG","category":"6","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"157","price":"10,40","priceperunity":"20,8\/KILO","product":"PAN RALLADO COMUN PAQUETE - 500 G","category":"6","brand":"MAM\u00c1 COCINA","supplier":"MOLINOS CA\u00d1UELAS"},
    {"id":"158","price":"10,90","priceperunity":"21,8\/KILO","product":"PAN RALLADO COMUN PAQUETE - 500 G","category":"6","brand":"PREFERIDO","supplier":"MOLINOS R\u00cdO DE LA PLATA"},
    {"id":"159","price":"10,55","priceperunity":"70,33\/KILO","product":"TOSTADAS CLASICAS LIVIANAS - 150 G","category":"6","brand":"BIMBO","supplier":"BIMBO DE ARGENTINA S.A."},

    {"id":"160","price":"12,50","priceperunity":"25\/LITRO","product":"ALCOHOL ETILICO 96 \u00b0 - 500 CM3","category":"7","brand":"MF","supplier":"FRADEALCO"},
    {"id":"161","price":"6,10","priceperunity":"81,33\/KILO","product":"ALGOD\u00d3N COMUN - 75 G","category":"7","brand":"ESTRELLA","supplier":"VICENTIN"},
    {"id":"162","price":"15,76","priceperunity":"15,76 \/LITRO","product":"CREMA DE ENJUAGUE O ACONDICIONADOR FAMILIAR CERAMIDAS+ARGININA - 1 LT","category":"7","brand":"PLUSBELLE","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"163","price":"17,30","priceperunity":"153,1\/LITRO","product":"DESODORANTE EN AEROSOL FEMENINO SO HAPPY - 113 G","category":"7","brand":"PLUSBELLE","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"164","price":"14,50","priceperunity":"290\/LITRO","product":"DESODORANTE FEMENINO ROLL ON CRYSTAL - 50 CM3","category":"7","brand":"REXONA","supplier":"UNILEVER"},
    {"id":"165","price":"15,00","priceperunity":"300\/LITRO","product":"DESODORANTE MASCULINO ROLL ON INVISIBLE - 50 CM3","category":"7","brand":"REXONA","supplier":"UNILEVER"},
    {"id":"166","price":"7,89","priceperunity":"87,67\/KILO","product":"JABON DE TOCADOR CAMPOS DE ENSUE\u00d1O 90GR - 3 UN","category":"7","brand":"LIMOL","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"167","price":"8,00","priceperunity":"88,89\/KILO","product":"JABON DE TOCADOR TE VERDE ALOE VERA 90GR - 3 UN","category":"7","brand":"SUAVE","supplier":"UNILEVER"},
    {"id":"168","price":"44,69","priceperunity":"1,24\/C\/U","product":"PA\u00d1ALES DESCARTABLES PARA BEBES ULTRA TRI PACK CHICO - 36 UN","category":"7","brand":"BABY SEC","supplier":"PAPELERA DEL PLATA"},
    {"id":"169","price":"44,69","priceperunity":"1,86\/C\/U","product":"PA\u00d1ALES DESCARTABLES PARA BEBES ULTRA TRI PACK EXTRA GRANDE - 24 UN","category":"7","brand":"BABY SEC","supplier":"PAPELERA DEL PLATA"},
    {"id":"170","price":"44,69","priceperunity":"1,86\/C\/U","product":"PA\u00d1ALES DESCARTABLES PARA BEBES ULTRA TRI PACK EXTRA-EXTRA GRANDE - 24 UN","category":"7","brand":"BABY SEC","supplier":"PAPELERA DEL PLATA"},
    {"id":"171","price":"44,69","priceperunity":"1,49\/C\/U","product":"PA\u00d1ALES DESCARTABLES PARA BEBES ULTRA TRI PACK GRANDE - 30 UN","category":"7","brand":"BABY SEC","supplier":"PAPELERA DEL PLATA"},
    {"id":"172","price":"44,69","priceperunity":"1,24\/C\/U","product":"PA\u00d1ALES DESCARTABLES PARA BEBES ULTRA TRI PACK MEDIANO - 36 UN","category":"7","brand":"BABY SEC","supplier":"PAPELERA DEL PLATA"},
    {"id":"173","price":"102,00","priceperunity":"2,32\/C\/U","product":"PA\u00d1ALES DESCARTABLES PARA BEBES CANT. EXTRA GRANDE - 44 UN","category":"7","brand":"PAMPERS BABYSAN","supplier":"PROCTER AND GAMBLE"},
    {"id":"174","price":"6,55","priceperunity":"72,78\/KILO","product":"PASTA DENTAL EN CREMA O GEL - 90 G","category":"7","brand":"KOLYNOS","supplier":"COLGATE PALMOLIVE S.A."},
    {"id":"175","price":"4,85","priceperunity":"53,89\/KILO","product":"PASTA DENTAL EN CREMA O GEL - 90 G","category":"7","brand":"ODOL","supplier":"COLGATE PALMOLIVE S.A."},
    {"id":"176","price":"27,45","priceperunity":"4,58\/C\/U","product":"PRESERVATIVOS SUPER FINOS 6 UNIDADES - 1 CAJA","category":"7","brand":"PRIME","supplier":"BUHLSA"},
    {"id":"177","price":"23,80","priceperunity":"3,97\/C\/U","product":"PRESERVATIVOS SUPER FINOS 6 UNIDADES - 1 CAJA","category":"7","brand":"TULIPAN","supplier":"KOPELCO"},
    {"id":"178","price":"15,76","priceperunity":"15,76\/LITRO","product":"SHAMPOO FAMILIAR CERAMIDAS+ARGININA - 1 LT","category":"7","brand":"PLUSBELLE","supplier":"ALICORP ARGENTINA S.C.A."},
    {"id":"179","price":"4,80","priceperunity":"0,6\/C\/U","product":"TOALLAS FEMENINAS NORMAL CON ALAS - 8 UN","category":"7","brand":"CALIPSO","supplier":"ALGODONERA ACONCAGUA SA"},
    {"id":"180","price":"5,39","priceperunity":"0,67\/C\/U","product":"TOALLAS FEMENINAS NORMAL CON ALAS COMFORT - 8 UN","category":"7","brand":"LADY SOFT","supplier":"PAPELERA DEL PLATA"},

    {"id":"181","price":"30,00","priceperunity":"30,00 \/KILO","product":"AJ\u00cd MORR\u00d3N FRESCO ROJO - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"182","price":"6,91","priceperunity":"6,91 \/KILO","product":"BATATA - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"183","price":"6,75","priceperunity":"6,75\/KILO","product":"CEBOLLA BLANCA - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"184","price":"11,00","priceperunity":"11,00 \/KILO","product":"LECHUGA CRIOLLA - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"185","price":"11,15","priceperunity":"11,15\/KILO","product":"MANZANA ROJA - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"186","price":"5,10","priceperunity":"5,10 \/KILO","product":"PAPA NEGRA - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"187","price":"9,60","priceperunity":"9,60 \/KILO","product":"PERA - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"188","price":"11,50","priceperunity":"11,50 \/KILO","product":"TOMATE REDONDO - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"189","price":"6,45","priceperunity":"6,45 \/KILO","product":"ZANAHORIA - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},
    {"id":"190","price":"9,00","priceperunity":"9,00 \/KILO","product":"ZAPALLO - 1 KG","category":"8","brand":"SIN MARCA (SUPERMERCADO)","supplier":"SIN MARCA (SUPERMERCADO)"},

    {"id":"191","price":"5,90","priceperunity":"","product":"BOLIGRAFO 4 UNIDADES","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"192","price":"11,90","priceperunity":"","product":"Bol\u00edgrafo BIC Round Stic Surtido x 4 (azul, rojo, negro y verde)","category":"9","brand":"BIC","supplier":"BIC ARGENTINA"},
    {"id":"193","price":"12,90","priceperunity":"","product":"CARPETA 9 3-AN X40CM F NEGRA 1 UNI","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"194","price":"11,00","priceperunity":"","product":"CRAYONES ALBA COLORSOL 12 UNIDADES","category":"9","brand":"ALBA","supplier":"INDUART"},
    {"id":"195","price":"5,50","priceperunity":"","product":"CRAYONES ALBA COLORSOL 6 UNIDADES","category":"9","brand":"ALBA","supplier":"INDUART"},
    {"id":"196","price":"11,99","priceperunity":"","product":"CUADERNO TAPA DURA ARA\u00d1A 42 HOJAS CUADRICULADO AZUL","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"197","price":"11,99","priceperunity":"","product":"CUADERNO TAPA DURA ARA\u00d1A 42 HOJAS RAYADO AZUL","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"198","price":"11,99","priceperunity":"","product":"CUADERNO TAPA DURA ARA\u00d1A 42 HOJAS RAYADO ROJO","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"199","price":"11,99","priceperunity":"","product":"CUADERNO TAPA DURA ARA\u00d1A 42 HOJAS RAYADO VERDE","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"200","price":"4,55","priceperunity":"","product":"CUADERNO TAPA FLEXIBLE 48 HOJAS CUADRICULADO","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"201","price":"4,55","priceperunity":"","product":"CUADERNO TAPA FLEXIBLE 48 HOJAS RAYADO","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"202","price":"3,00","priceperunity":"","product":"GOMA TINTA-LAPIZ Duo Gom","category":"9","brand":"MAPED ARGENTINA S.A.","supplier":"MAPED"},
    {"id":"203","price":"64,00","priceperunity":"","product":"GUARDAPOLVO RECTO UNISEX 520 TALLE 10","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"204","price":"73,00","priceperunity":"","product":"GUARDAPOLVO RECTO UNISEX     520 TALLE 12","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"205","price":"39,00","priceperunity":"","product":"GUARDAPOLVO RECTO UNISEX     520 TALLE 6","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"206","price":"55,00","priceperunity":"","product":"GUARDAPOLVO RECTO UNISEX     520 TALLE 8","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"207","price":"6,90","priceperunity":"","product":"KIT 9 DE 3 PINCELES 3 UNIDADES","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"208","price":"9,90","priceperunity":"","product":"L\u00c1PICES DE COLOR LAP. COLOR GREENCASTLE x 12 col largos","category":"9","brand":"GREENCASTLE","supplier":"A.W. FABER CASTELL ARG.S.A."},
    {"id":"209","price":"4,50","priceperunity":"","product":"L\u00c1PICES DE GRAFITO ECOL\u00c1PICES DE GRAFITO 1205 MAX X 3","category":"9","brand":"FABER CASTELL","supplier":"A.W. FABER CASTELL ARG.S.A."},
    {"id":"210","price":"6,00","priceperunity":"","product":"L\u00c1PICES DE GRAFITO ECOL\u00c1PICES DE GRAFITO 1205 MAX X 4","category":"9","brand":"FABER CASTELL","supplier":"A.W. FABER CASTELL ARG.S.A."},
    {"id":"211","price":"7,90","priceperunity":"","product":"LAPIZ CORRECTOR BEROL PUNTA METALICA","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"212","price":"3,99","priceperunity":"","product":"MAPAS RIVADAVIA NRO 3 (ARGENTINA Y OTROS) x 5 mapas","category":"9","brand":"ESTRADA","supplier":"ANGEL ESTRADA Y CIA S.A."},
    {"id":"213","price":"3,50","priceperunity":"","product":"MARCADOR 9 6 UNIDADES","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"214","price":"10,19","priceperunity":"","product":"MINI MARCADORES BOX 10 UNIDADES","category":"9","brand":"SYLVAPEN","supplier":"NEWELL RUBBERMAID"},
    {"id":"215","price":"90,00","priceperunity":"","product":"MOCHILA LISA 9 GRANDE CON BOLSILLO","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"216","price":"0,90","priceperunity":"","product":"Papel Glace Lustre x 10 hjas Papel Glace Lustre x 10 hjas","category":"9","brand":"LUMA","supplier":"LUMA"},
    {"id":"217","price":"1,10","priceperunity":"","product":"Papel Glace Metalizado x 10 Hjas ","category":"9","brand":"LUMA","supplier":"LUMA"},
    {"id":"218","price":"35,00","priceperunity":"","product":"REPUESTO GLORIA CUADRICULADO 400 HOJAS","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"219","price":"35,00","priceperunity":"","product":"REPUESTO GLORIA RAYADO 400 HOJAS","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"220","price":"11,15","priceperunity":"","product":"REPUESTO HOJAS N\u00ba 3 CUADRICULADO 96 HOJAS","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"221","price":"11,15","priceperunity":"","product":"REPUESTO HOJAS N\u00ba 3 RAYADO 96 HOJAS","category":"9","brand":"GLORIA O AM\u00c9RICA","supplier":"LEDESMA\/ANGEL ESTRADA"},
    {"id":"222","price":"3,39","priceperunity":"","product":"SACAPUNTAS BOOGY","category":"9","brand":"MAPED ARGENTINA S.A.","supplier":"MAPED"},
    {"id":"223","price":"5,50","priceperunity":"","product":"TEMPERA ALBAMATIC 5 X 8 GRS","category":"9","brand":"ALBA","supplier":"INDUART"},
    {"id":"224","price":"5,90","priceperunity":"","product":"Tijera Start 12 cm","category":"9","brand":"GEN\u00c9RICO","supplier":""},
    {"id":"225","price":"2,55","priceperunity":"","product":"VOLIGOMA\u00ae 30ML BLISTER ADHESIVO SINT\u00c9TICO","category":"9","brand":"VOLIGOMA","supplier":"AKAPOL"}
  ];

  return {
    all: function() {
      //window.localStorage.setItem("products", JSON.stringify(products));
      return products;
    },
    getObjects: function(obj, key, val){
      var objects = [];
      for (var i in obj) {
          if (!obj.hasOwnProperty(i)) continue;
          if (typeof obj[i] == 'object') {
              objects = objects.concat(this.getObjects(obj[i], key, val));
          } else if (i == key && obj[key] == val) {
              objects.push(obj);
          }
      }
      return objects;
    },
    get: function(productId) {
      return products[productId - 1];
    }
  };

});
